### ISSUE TITLE
Amplitude plugin has no reset function?

### ISSUE THREAD

**Issue by lilidotshi** [segment-integrations/analytics-swift-amplitude#4]
Hi! Just noticed that the amplitude swift plugin does not implement the reset function like the objc version does https://github.com/segment-integrations/analytics-ios-integration-amplitude/blame/master/Pod/Classes/SEGAmplitudeIntegration.m. Is this going to get added soon?

**Comment by alanjcharles** [comment]
Hi @lilidotshi thanks for reaching out! The Amplitude plugin for Swift does not provide the same functionality as the classic Analytics iOS Amplitude integration. The Amplitude Swift plugin does not rely on or bundle the Amplitude SDK in traditional device mode fashion. Instead, it tracks `sessions`, adds the session tracking data to your Segment events, and sends the payload to Amplitude via a Cloud Mode connection. We currently do not have a `reset()` function since there is no Amplitude equivalent to tie it to (since Amplitude isn't bundled).  [Please see this documentation](https://segment.com/docs/connections/destinations/catalog/actions-amplitude/) for a more in-depth explanation. I hope this helps! Please feel free to reopen this issue if something isn't clear or reach out to `friends@segment.com` for more detailed troubleshooting help. Thanks again!
